GCC= gcc
FLAGS= -Wall -Werror -Wextra
DEPS= ../grep/s21_func.h
FILES_CAT= ../grep/s21_grep.c ../grep/s21_func.c ../grep/s21_grep.h
NAME_CAT= -o ../grep/s21_grep
s21_grep:
	rm -rf ../grep/s21_grep
	${GCC} ${FLAGS} ${FILES_CAT} ${NAME_CAT}